export type Country = {
  code: string,
  name: string,
  nativeName: string,
  dialCode: string,
  flag: string,
};

export const countries: Country[] = [
  { code: 'AF', name: 'Afghanistan', nativeName: 'افغانستان', dialCode: '+93', flag: '🇦🇫' },
  { code: 'AX', name: 'Åland Islands', nativeName: 'Åland', dialCode: '+358', flag: '🇦🇽' },
  { code: 'AL', name: 'Albania', nativeName: 'Shqipëria', dialCode: '+355', flag: '🇦🇱' },
  { code: 'DZ', name: 'Algeria', nativeName: 'الجزائر', dialCode: '+213', flag: '🇩🇿' },
  { code: 'AS', name: 'American Samoa', nativeName: 'American Samoa', dialCode: '+1684', flag: '🇦🇸' },
  { code: 'AD', name: 'Andorra', nativeName: 'Andorra', dialCode: '+376', flag: '🇦🇩' },
  { code: 'AO', name: 'Angola', nativeName: 'Angola', dialCode: '+244', flag: '🇦🇴' },
  { code: 'AI', name: 'Anguilla', nativeName: 'Anguilla', dialCode: '+1264', flag: '🇦🇮' },
  { code: 'AQ', name: 'Antarctica', nativeName: 'Antarctica', dialCode: '+672', flag: '🇦🇶' },
  { code: 'AG', name: 'Antigua and Barbuda', nativeName: 'Antigua and Barbuda', dialCode: '+1268', flag: '🇦🇬' },
  { code: 'AR', name: 'Argentina', nativeName: 'Argentina', dialCode: '+54', flag: '🇦🇷' },
  { code: 'AM', name: 'Armenia', nativeName: 'Հայաստան', dialCode: '+374', flag: '🇦🇲' },
  { code: 'AW', name: 'Aruba', nativeName: 'Aruba', dialCode: '+297', flag: '🇦🇼' },
  { code: 'AU', name: 'Australia', nativeName: 'Australia', dialCode: '+61', flag: '🇦🇺' },
  { code: 'AT', name: 'Austria', nativeName: 'Österreich', dialCode: '+43', flag: '🇦🇹' },
  { code: 'AZ', name: 'Azerbaijan', nativeName: 'Azərbaycan', dialCode: '+994', flag: '🇦🇿' },
  { code: 'BS', name: 'Bahamas', nativeName: 'Bahamas', dialCode: '+1242', flag: '🇧🇸' },
  { code: 'BH', name: 'Bahrain', nativeName: 'البحرين', dialCode: '+973', flag: '🇧🇭' },
  { code: 'BD', name: 'Bangladesh', nativeName: 'বাংলাদেশ', dialCode: '+880', flag: '🇧🇩' },
  { code: 'BB', name: 'Barbados', nativeName: 'Barbados', dialCode: '+1246', flag: '🇧🇧' },
  { code: 'BY', name: 'Belarus', nativeName: 'Беларусь', dialCode: '+375', flag: '🇧🇾' },
  { code: 'BE', name: 'Belgium', nativeName: 'België', dialCode: '+32', flag: '🇧🇪' },
  { code: 'BZ', name: 'Belize', nativeName: 'Belize', dialCode: '+501', flag: '🇧🇿' },
  { code: 'BJ', name: 'Benin', nativeName: 'Bénin', dialCode: '+229', flag: '🇧🇯' },
  { code: 'BM', name: 'Bermuda', nativeName: 'Bermuda', dialCode: '+1441', flag: '🇧🇲' },
  { code: 'BT', name: 'Bhutan', nativeName: 'འབྲུག་ཡུལ', dialCode: '+975', flag: '🇧🇹' },
  { code: 'BO', name: 'Bolivia', nativeName: 'Bolivia', dialCode: '+591', flag: '🇧🇴' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', nativeName: 'Bonaire', dialCode: '+599', flag: '🇧🇶' },
  { code: 'BA', name: 'Bosnia and Herzegovina', nativeName: 'Bosna i Hercegovina', dialCode: '+387', flag: '🇧🇦' },
  { code: 'BW', name: 'Botswana', nativeName: 'Botswana', dialCode: '+267', flag: '🇧🇼' },
  { code: 'BV', name: 'Bouvet Island', nativeName: 'Bouvetøya', dialCode: '+47', flag: '🇧🇻' },
  { code: 'BR', name: 'Brazil', nativeName: 'Brasil', dialCode: '+55', flag: '🇧🇷' },
  { code: 'IO', name: 'British Indian Ocean Territory', nativeName: 'British Indian Ocean Territory', dialCode: '+246', flag: '🇮🇴' },
  { code: 'BN', name: 'Brunei Darussalam', nativeName: 'Brunei', dialCode: '+673', flag: '🇧🇳' },
  { code: 'BG', name: 'Bulgaria', nativeName: 'България', dialCode: '+359', flag: '🇧🇬' },
  { code: 'BF', name: 'Burkina Faso', nativeName: 'Burkina Faso', dialCode: '+226', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', nativeName: 'Uburundi', dialCode: '+257', flag: '🇧🇮' },
  { code: 'CV', name: 'Cabo Verde', nativeName: 'Kabu Verdi', dialCode: '+238', flag: '🇨🇻' },
  { code: 'KH', name: 'Cambodia', nativeName: 'កម្ពុជា', dialCode: '+855', flag: '🇰🇭' },
  { code: 'CM', name: 'Cameroon', nativeName: 'Cameroun', dialCode: '+237', flag: '🇨🇲' },
  { code: 'CA', name: 'Canada', nativeName: 'Canada', dialCode: '+1', flag: '🇨🇦' },
  { code: 'KY', name: 'Cayman Islands', nativeName: 'Cayman Islands', dialCode: '+1345', flag: '🇰🇾' },
  { code: 'CF', name: 'Central African Republic', nativeName: 'République centrafricaine', dialCode: '+236', flag: '🇨🇫' },
  { code: 'TD', name: 'Chad', nativeName: 'Tchad', dialCode: '+235', flag: '🇹🇩' },
  { code: 'CL', name: 'Chile', nativeName: 'Chile', dialCode: '+56', flag: '🇨🇱' },
  { code: 'CN', name: 'China', nativeName: '中国', dialCode: '+86', flag: '🇨🇳' },
  { code: 'CX', name: 'Christmas Island', nativeName: 'Christmas Island', dialCode: '+61', flag: '🇨🇽' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', nativeName: 'Cocos (Keeling) Islands', dialCode: '+61', flag: '🇨🇨' },
  { code: 'CO', name: 'Colombia', nativeName: 'Colombia', dialCode: '+57', flag: '🇨🇴' },
  { code: 'KM', name: 'Comoros', nativeName: 'جزر القمر', dialCode: '+269', flag: '🇰🇲' },
  { code: 'CG', name: 'Congo', nativeName: 'Congo', dialCode: '+242', flag: '🇨🇬' },
  { code: 'CD', name: 'Congo, Democratic Republic of the', nativeName: 'RDC', dialCode: '+243', flag: '🇨🇩' },
  { code: 'CK', name: 'Cook Islands', nativeName: 'Cook Islands', dialCode: '+682', flag: '🇨🇰' },
  { code: 'CR', name: 'Costa Rica', nativeName: 'Costa Rica', dialCode: '+506', flag: '🇨🇷' },
  { code: 'CI', name: "Côte d'Ivoire", nativeName: "Côte d'Ivoire", dialCode: '+225', flag: '🇨🇮' },
  { code: 'HR', name: 'Croatia', nativeName: 'Hrvatska', dialCode: '+385', flag: '🇭🇷' },
  { code: 'CU', name: 'Cuba', nativeName: 'Cuba', dialCode: '+53', flag: '🇨🇺' },
  { code: 'CW', name: 'Curaçao', nativeName: 'Curaçao', dialCode: '+599', flag: '🇨🇼' },
  { code: 'CY', name: 'Cyprus', nativeName: 'Kýpros', dialCode: '+357', flag: '🇨🇾' },
  { code: 'CZ', name: 'Czechia', nativeName: 'Česko', dialCode: '+420', flag: '🇨🇿' },
  { code: 'DK', name: 'Denmark', nativeName: 'Danmark', dialCode: '+45', flag: '🇩🇰' },
  { code: 'DJ', name: 'Djibouti', nativeName: 'Djibouti', dialCode: '+253', flag: '🇩🇯' },
  { code: 'DM', name: 'Dominica', nativeName: 'Dominica', dialCode: '+1767', flag: '🇩🇲' },
  { code: 'DO', name: 'Dominican Republic', nativeName: 'República Dominicana', dialCode: '+1809', flag: '🇩🇴' },
  { code: 'EC', name: 'Ecuador', nativeName: 'Ecuador', dialCode: '+593', flag: '🇪🇨' },
  { code: 'EG', name: 'Egypt', nativeName: 'مصر', dialCode: '+20', flag: '🇪🇬' },
  { code: 'SV', name: 'El Salvador', nativeName: 'El Salvador', dialCode: '+503', flag: '🇸🇻' },
  { code: 'GQ', name: 'Equatorial Guinea', nativeName: 'Guinea Ecuatorial', dialCode: '+240', flag: '🇬🇶' },
  { code: 'ER', name: 'Eritrea', nativeName: 'ኤርትራ', dialCode: '+291', flag: '🇪🇷' },
  { code: 'EE', name: 'Estonia', nativeName: 'Eesti', dialCode: '+372', flag: '🇪🇪' },
  { code: 'SZ', name: 'Eswatini', nativeName: 'eSwatini', dialCode: '+268', flag: '🇸🇿' },
  { code: 'ET', name: 'Ethiopia', nativeName: 'ኢትዮጵያ', dialCode: '+251', flag: '🇪🇹' },
  { code: 'FK', name: 'Falkland Islands (Malvinas)', nativeName: 'Falkland Islands', dialCode: '+500', flag: '🇫🇰' },
  { code: 'FO', name: 'Faroe Islands', nativeName: 'Føroyar', dialCode: '+298', flag: '🇫🇴' },
  { code: 'FJ', name: 'Fiji', nativeName: 'Viti', dialCode: '+679', flag: '🇫🇯' },
  { code: 'FI', name: 'Finland', nativeName: 'Suomi', dialCode: '+358', flag: '🇫🇮' },
  { code: 'FR', name: 'France', nativeName: 'France', dialCode: '+33', flag: '🇫🇷' },
  { code: 'GF', name: 'French Guiana', nativeName: 'Guyane française', dialCode: '+594', flag: '🇬🇫' },
  { code: 'PF', name: 'French Polynesia', nativeName: 'Polynésie française', dialCode: '+689', flag: '🇵🇫' },
  { code: 'TF', name: 'French Southern Territories', nativeName: 'Terres australes françaises', dialCode: '+262', flag: '🇹🇫' },
  { code: 'GA', name: 'Gabon', nativeName: 'Gabon', dialCode: '+241', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambia', nativeName: 'Gambia', dialCode: '+220', flag: '🇬🇲' },
  { code: 'GE', name: 'Georgia', nativeName: 'საქართველო', dialCode: '+995', flag: '🇬🇪' },
  { code: 'DE', name: 'Germany', nativeName: 'Deutschland', dialCode: '+49', flag: '🇩🇪' },
  { code: 'GH', name: 'Ghana', nativeName: 'Ghana', dialCode: '+233', flag: '🇬🇭' },
  { code: 'GI', name: 'Gibraltar', nativeName: 'Gibraltar', dialCode: '+350', flag: '🇬🇮' },
  { code: 'GR', name: 'Greece', nativeName: 'Ελλάδα', dialCode: '+30', flag: '🇬🇷' },
  { code: 'GL', name: 'Greenland', nativeName: 'Kalaallit Nunaat', dialCode: '+299', flag: '🇬🇱' },
  { code: 'GD', name: 'Grenada', nativeName: 'Grenada', dialCode: '+1473', flag: '🇬🇩' },
  { code: 'GP', name: 'Guadeloupe', nativeName: 'Guadeloupe', dialCode: '+590', flag: '🇬🇵' },
  { code: 'GU', name: 'Guam', nativeName: 'Guam', dialCode: '+1671', flag: '🇬🇺' },
  { code: 'GT', name: 'Guatemala', nativeName: 'Guatemala', dialCode: '+502', flag: '🇬🇹' },
  { code: 'GG', name: 'Guernsey', nativeName: 'Guernsey', dialCode: '+44', flag: '🇬🇬' },
  { code: 'GN', name: 'Guinea', nativeName: 'Guinée', dialCode: '+224', flag: '🇬🇳' },
  { code: 'GW', name: 'Guinea-Bissau', nativeName: 'Guiné-Bissau', dialCode: '+245', flag: '🇬🇼' },
  { code: 'GY', name: 'Guyana', nativeName: 'Guyana', dialCode: '+592', flag: '🇬🇾' },
  { code: 'HT', name: 'Haiti', nativeName: 'Haïti', dialCode: '+509', flag: '🇭🇹' },
  { code: 'HM', name: 'Heard Island and McDonald Islands', nativeName: 'Heard Island and McDonald Islands', dialCode: '+672', flag: '🇭🇲' },
  { code: 'VA', name: 'Holy See', nativeName: 'Vaticano', dialCode: '+379', flag: '🇻🇦' },
  { code: 'HN', name: 'Honduras', nativeName: 'Honduras', dialCode: '+504', flag: '🇭🇳' },
  { code: 'HK', name: 'Hong Kong', nativeName: '香港', dialCode: '+852', flag: '🇭🇰' },
  { code: 'HU', name: 'Hungary', nativeName: 'Magyarország', dialCode: '+36', flag: '🇭🇺' },
  { code: 'IS', name: 'Iceland', nativeName: 'Ísland', dialCode: '+354', flag: '🇮🇸' },
  { code: 'IN', name: 'India', nativeName: 'भारत', dialCode: '+91', flag: '🇮🇳' },
  { code: 'ID', name: 'Indonesia', nativeName: 'Indonesia', dialCode: '+62', flag: '🇮🇩' },
  { code: 'IR', name: 'Iran', nativeName: 'إيران', dialCode: '+98', flag: '🇮🇷' },
  { code: 'IQ', name: 'Iraq', nativeName: 'العراق', dialCode: '+964', flag: '🇮🇶' },
  { code: 'IE', name: 'Ireland', nativeName: 'Éire', dialCode: '+353', flag: '🇮🇪' },
  { code: 'IM', name: 'Isle of Man', nativeName: 'Isle of Man', dialCode: '+44', flag: '🇮🇲' },
  { code: 'IL', name: 'Israel', nativeName: 'ישראל', dialCode: '+972', flag: '🇮🇱' },
  { code: 'IT', name: 'Italy', nativeName: 'Italia', dialCode: '+39', flag: '🇮🇹' },
  { code: 'JM', name: 'Jamaica', nativeName: 'Jamaica', dialCode: '+1876', flag: '🇯🇲' },
  { code: 'JP', name: 'Japan', nativeName: '日本', dialCode: '+81', flag: '🇯🇵' },
  { code: 'JE', name: 'Jersey', nativeName: 'Jersey', dialCode: '+44', flag: '🇯🇪' },
  { code: 'JO', name: 'Jordan', nativeName: 'الأردن', dialCode: '+962', flag: '🇯🇴' },
  { code: 'KZ', name: 'Kazakhstan', nativeName: 'Қазақстан', dialCode: '+7', flag: '🇰🇿' },
  { code: 'KE', name: 'Kenya', nativeName: 'Kenya', dialCode: '+254', flag: '🇰🇪' },
  { code: 'KI', name: 'Kiribati', nativeName: 'Kiribati', dialCode: '+686', flag: '🇰🇮' },
  { code: 'KP', name: "Korea, Democratic People's Republic of", nativeName: '조선', dialCode: '+850', flag: '🇰🇵' },
  { code: 'KR', name: 'Korea, Republic of', nativeName: '대한민국', dialCode: '+82', flag: '🇰🇷' },
  { code: 'KW', name: 'Kuwait', nativeName: 'الكويت', dialCode: '+965', flag: '🇰🇼' },
  { code: 'KG', name: 'Kyrgyzstan', nativeName: 'Кыргызстан', dialCode: '+996', flag: '🇰🇬' },
  { code: 'LA', name: "Lao People's Democratic Republic", nativeName: 'ລາວ', dialCode: '+856', flag: '🇱🇦' },
  { code: 'LV', name: 'Latvia', nativeName: 'Latvija', dialCode: '+371', flag: '🇱🇻' },
  { code: 'LB', name: 'Lebanon', nativeName: 'لبنان', dialCode: '+961', flag: '🇱🇧' },
  { code: 'LS', name: 'Lesotho', nativeName: 'Lesotho', dialCode: '+266', flag: '🇱🇸' },
  { code: 'LR', name: 'Liberia', nativeName: 'Liberia', dialCode: '+231', flag: '🇱🇷' },
  { code: 'LY', name: 'Libya', nativeName: 'ليبيا', dialCode: '+218', flag: '🇱🇾' },
  { code: 'LI', name: 'Liechtenstein', nativeName: 'Liechtenstein', dialCode: '+423', flag: '🇱🇮' },
  { code: 'LT', name: 'Lithuania', nativeName: 'Lietuva', dialCode: '+370', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxembourg', nativeName: 'Lëtzebuerg', dialCode: '+352', flag: '🇱🇺' },
  { code: 'MO', name: 'Macao', nativeName: '澳門', dialCode: '+853', flag: '🇲🇴' },
  { code: 'MG', name: 'Madagascar', nativeName: 'Madagasikara', dialCode: '+261', flag: '🇲🇬' },
  { code: 'MW', name: 'Malawi', nativeName: 'Malawi', dialCode: '+265', flag: '🇲🇼' },
  { code: 'MY', name: 'Malaysia', nativeName: 'Malaysia', dialCode: '+60', flag: '🇲🇾' },
  { code: 'MV', name: 'Maldives', nativeName: 'ދިވެހިރާއްޖެ', dialCode: '+960', flag: '🇲🇻' },
  { code: 'ML', name: 'Mali', nativeName: 'Mali', dialCode: '+223', flag: '🇲🇱' },
  { code: 'MT', name: 'Malta', nativeName: 'Malta', dialCode: '+356', flag: '🇲🇹' },
  { code: 'MH', name: 'Marshall Islands', nativeName: 'Aorōkin M̧ajeļ', dialCode: '+692', flag: '🇲🇭' },
  { code: 'MQ', name: 'Martinique', nativeName: 'Martinique', dialCode: '+596', flag: '🇲🇶' },
  { code: 'MR', name: 'Mauritania', nativeName: 'موريتانيا', dialCode: '+222', flag: '🇲🇷' },
  { code: 'MU', name: 'Mauritius', nativeName: 'Maurice', dialCode: '+230', flag: '🇲🇺' },
  { code: 'YT', name: 'Mayotte', nativeName: 'Mayotte', dialCode: '+262', flag: '🇾🇹' },
  { code: 'MX', name: 'Mexico', nativeName: 'México', dialCode: '+52', flag: '🇲🇽' },
  { code: 'FM', name: 'Micronesia (Federated States of)', nativeName: 'Micronesia', dialCode: '+691', flag: '🇫🇲' },
  { code: 'MD', name: 'Moldova, Republic of', nativeName: 'Moldova', dialCode: '+373', flag: '🇲🇩' },
  { code: 'MC', name: 'Monaco', nativeName: 'Monaco', dialCode: '+377', flag: '🇲🇨' },
  { code: 'MN', name: 'Mongolia', nativeName: 'Монгол улс', dialCode: '+976', flag: '🇲🇳' },
  { code: 'ME', name: 'Montenegro', nativeName: 'Crna Gora', dialCode: '+382', flag: '🇲🇪' },
  { code: 'MS', name: 'Montserrat', nativeName: 'Montserrat', dialCode: '+1664', flag: '🇲🇸' },
  { code: 'MA', name: 'Morocco', nativeName: 'المغرب', dialCode: '+212', flag: '🇲🇦' },
  { code: 'MZ', name: 'Mozambique', nativeName: 'Moçambique', dialCode: '+258', flag: '🇲🇿' },
  { code: 'MM', name: 'Myanmar', nativeName: 'မြန်မာ', dialCode: '+95', flag: '🇲🇲' },
  { code: 'NA', name: 'Namibia', nativeName: 'Namibia', dialCode: '+264', flag: '🇳🇦' },
  { code: 'NR', name: 'Nauru', nativeName: 'Naoero', dialCode: '+674', flag: '🇳🇷' },
  { code: 'NP', name: 'Nepal', nativeName: 'नेपाल', dialCode: '+977', flag: '🇳🇵' },
  { code: 'NL', name: 'Netherlands', nativeName: 'Nederland', dialCode: '+31', flag: '🇳🇱' },
  { code: 'NC', name: 'New Caledonia', nativeName: 'Nouvelle-Calédonie', dialCode: '+687', flag: '🇳🇨' },
  { code: 'NZ', name: 'New Zealand', nativeName: 'Aotearoa', dialCode: '+64', flag: '🇳🇿' },
  { code: 'NI', name: 'Nicaragua', nativeName: 'Nicaragua', dialCode: '+505', flag: '🇳🇮' },
  { code: 'NE', name: 'Niger', nativeName: 'Niger', dialCode: '+227', flag: '🇳🇪' },
  { code: 'NG', name: 'Nigeria', nativeName: 'Nigeria', dialCode: '+234', flag: '🇳🇬' },
  { code: 'NU', name: 'Niue', nativeName: 'Niuē', dialCode: '+683', flag: '🇳🇺' },
  { code: 'NF', name: 'Norfolk Island', nativeName: 'Norfolk Island', dialCode: '+672', flag: '🇳🇫' },
  { code: 'MK', name: 'North Macedonia', nativeName: 'Северна Македонија', dialCode: '+389', flag: '🇲🇰' },
  { code: 'MP', name: 'Northern Mariana Islands', nativeName: 'Northern Mariana Islands', dialCode: '+1670', flag: '🇲🇵' },
  { code: 'NO', name: 'Norway', nativeName: 'Norge', dialCode: '+47', flag: '🇳🇴' },
  { code: 'OM', name: 'Oman', nativeName: 'عُمان', dialCode: '+968', flag: '🇴🇲' },
  { code: 'PK', name: 'Pakistan', nativeName: 'پاکستان', dialCode: '+92', flag: '🇵🇰' },
  { code: 'PW', name: 'Palau', nativeName: 'Belau', dialCode: '+680', flag: '🇵🇼' },
  { code: 'PS', name: 'Palestine, State of', nativeName: 'فلسطين', dialCode: '+970', flag: '🇵🇸' },
  { code: 'PA', name: 'Panama', nativeName: 'Panamá', dialCode: '+507', flag: '🇵🇦' },
  { code: 'PG', name: 'Papua New Guinea', nativeName: 'Papua Niugini', dialCode: '+675', flag: '🇵🇬' },
  { code: 'PY', name: 'Paraguay', nativeName: 'Paraguay', dialCode: '+595', flag: '🇵🇾' },
  { code: 'PE', name: 'Peru', nativeName: 'Perú', dialCode: '+51', flag: '🇵🇪' },
  { code: 'PH', name: 'Philippines', nativeName: 'Pilipinas', dialCode: '+63', flag: '🇵🇭' },
  { code: 'PN', name: 'Pitcairn', nativeName: 'Pitcairn Islands', dialCode: '+64', flag: '🇵🇳' },
  { code: 'PL', name: 'Poland', nativeName: 'Polska', dialCode: '+48', flag: '🇵🇱' },
  { code: 'PT', name: 'Portugal', nativeName: 'Portugal', dialCode: '+351', flag: '🇵🇹' },
  { code: 'PR', name: 'Puerto Rico', nativeName: 'Puerto Rico', dialCode: '+1', flag: '🇵🇷' },
  { code: 'QA', name: 'Qatar', nativeName: 'قطر', dialCode: '+974', flag: '🇶🇦' },
  { code: 'RE', name: 'Réunion', nativeName: 'La Réunion', dialCode: '+262', flag: '🇷🇪' },
  { code: 'RO', name: 'Romania', nativeName: 'România', dialCode: '+40', flag: '🇷🇴' },
  { code: 'RU', name: 'Russian Federation', nativeName: 'Россия', dialCode: '+7', flag: '🇷🇺' },
  { code: 'RW', name: 'Rwanda', nativeName: 'Rwanda', dialCode: '+250', flag: '🇷🇼' },
  { code: 'BL', name: 'Saint Barthélemy', nativeName: 'Saint-Barthélemy', dialCode: '+590', flag: '🇧🇱' },
  { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha', nativeName: 'Saint Helena', dialCode: '+290', flag: '🇸🇭' },
  { code: 'KN', name: 'Saint Kitts and Nevis', nativeName: 'Saint Kitts and Nevis', dialCode: '+1869', flag: '🇰🇳' },
  { code: 'LC', name: 'Saint Lucia', nativeName: 'Saint Lucia', dialCode: '+1758', flag: '🇱🇨' },
  { code: 'MF', name: 'Saint Martin (French part)', nativeName: 'Saint-Martin', dialCode: '+590', flag: '🇲🇫' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', nativeName: 'Saint-Pierre-et-Miquelon', dialCode: '+508', flag: '🇵🇲' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', nativeName: 'Saint Vincent and the Grenadines', dialCode: '+1784', flag: '🇻🇨' },
  { code: 'WS', name: 'Samoa', nativeName: 'Samoa', dialCode: '+685', flag: '🇼🇸' },
  { code: 'SM', name: 'San Marino', nativeName: 'San Marino', dialCode: '+378', flag: '🇸🇲' },
  { code: 'ST', name: 'Sao Tome and Principe', nativeName: 'São Tomé e Príncipe', dialCode: '+239', flag: '🇸🇹' },
  { code: 'SA', name: 'Saudi Arabia', nativeName: 'المملكة العربية السعودية', dialCode: '+966', flag: '🇸🇦' },
  { code: 'SN', name: 'Senegal', nativeName: 'Sénégal', dialCode: '+221', flag: '🇸🇳' },
  { code: 'RS', name: 'Serbia', nativeName: 'Србија', dialCode: '+381', flag: '🇷🇸' },
  { code: 'SC', name: 'Seychelles', nativeName: 'Seychelles', dialCode: '+248', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leone', nativeName: 'Sierra Leone', dialCode: '+232', flag: '🇸🇱' },
  { code: 'SG', name: 'Singapore', nativeName: 'Singapore', dialCode: '+65', flag: '🇸🇬' },
  { code: 'SX', name: 'Sint Maarten (Dutch part)', nativeName: 'Sint Maarten', dialCode: '+1721', flag: '🇸🇽' },
  { code: 'SK', name: 'Slovakia', nativeName: 'Slovensko', dialCode: '+421', flag: '🇸🇰' },
  { code: 'SI', name: 'Slovenia', nativeName: 'Slovenija', dialCode: '+386', flag: '🇸🇮' },
  { code: 'SB', name: 'Solomon Islands', nativeName: 'Solomon Islands', dialCode: '+677', flag: '🇸🇧' },
  { code: 'SO', name: 'Somalia', nativeName: 'Soomaaliya', dialCode: '+252', flag: '🇸🇴' },
  { code: 'ZA', name: 'South Africa', nativeName: 'South Africa', dialCode: '+27', flag: '🇿🇦' },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands', nativeName: 'South Georgia', dialCode: '+500', flag: '🇬🇸' },
  { code: 'SS', name: 'South Sudan', nativeName: 'South Sudan', dialCode: '+211', flag: '🇸🇸' },
  { code: 'ES', name: 'Spain', nativeName: 'España', dialCode: '+34', flag: '🇪🇸' },
  { code: 'LK', name: 'Sri Lanka', nativeName: 'ශ්‍රී ලංකාව', dialCode: '+94', flag: '🇱🇰' },
  { code: 'SD', name: 'Sudan', nativeName: 'السودان', dialCode: '+249', flag: '🇸🇩' },
  { code: 'SR', name: 'Suriname', nativeName: 'Suriname', dialCode: '+597', flag: '🇸🇷' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', nativeName: 'Svalbard og Jan Mayen', dialCode: '+47', flag: '🇸🇯' },
  { code: 'SE', name: 'Sweden', nativeName: 'Sverige', dialCode: '+46', flag: '🇸🇪' },
  { code: 'CH', name: 'Switzerland', nativeName: 'Schweiz', dialCode: '+41', flag: '🇨🇭' },
  { code: 'SY', name: 'Syrian Arab Republic', nativeName: 'سوريا', dialCode: '+963', flag: '🇸🇾' },
  { code: 'TW', name: 'Taiwan', nativeName: '台灣', dialCode: '+886', flag: '🇹🇼' },
  { code: 'TJ', name: 'Tajikistan', nativeName: 'Тоҷикистон', dialCode: '+992', flag: '🇹🇯' },
  { code: 'TZ', name: 'Tanzania, United Republic of', nativeName: 'Tanzania', dialCode: '+255', flag: '🇹🇿' },
  { code: 'TH', name: 'Thailand', nativeName: 'ประเทศไทย', dialCode: '+66', flag: '🇹🇭' },
  { code: 'TL', name: 'Timor-Leste', nativeName: 'Timor-Leste', dialCode: '+670', flag: '🇹🇱' },
  { code: 'TG', name: 'Togo', nativeName: 'Togo', dialCode: '+228', flag: '🇹🇬' },
  { code: 'TK', name: 'Tokelau', nativeName: 'Tokelau', dialCode: '+690', flag: '🇹🇰' },
  { code: 'TO', name: 'Tonga', nativeName: 'Tonga', dialCode: '+676', flag: '🇹🇴' },
  { code: 'TT', name: 'Trinidad and Tobago', nativeName: 'Trinidad and Tobago', dialCode: '+1868', flag: '🇹🇹' },
  { code: 'TN', name: 'Tunisia', nativeName: 'تونس', dialCode: '+216', flag: '🇹🇳' },
  { code: 'TR', name: 'Turkey', nativeName: 'Türkiye', dialCode: '+90', flag: '🇹🇷' },
  { code: 'TM', name: 'Turkmenistan', nativeName: 'Türkmenistan', dialCode: '+993', flag: '🇹🇲' },
  { code: 'TC', name: 'Turks and Caicos Islands', nativeName: 'Turks and Caicos Islands', dialCode: '+1649', flag: '🇹🇨' },
  { code: 'TV', name: 'Tuvalu', nativeName: 'Tuvalu', dialCode: '+688', flag: '🇹🇻' },
  { code: 'UG', name: 'Uganda', nativeName: 'Uganda', dialCode: '+256', flag: '🇺🇬' },
  { code: 'UA', name: 'Ukraine', nativeName: 'Україна', dialCode: '+380', flag: '🇺🇦' },
  { code: 'AE', name: 'United Arab Emirates', nativeName: 'الإمارات العربية المتحدة', dialCode: '+971', flag: '🇦🇪' },
  { code: 'GB', name: 'United Kingdom', nativeName: 'United Kingdom', dialCode: '+44', flag: '🇬🇧' },
  { code: 'US', name: 'United States', nativeName: 'United States', dialCode: '+1', flag: '🇺🇸' },
  { code: 'UM', name: 'United States Minor Outlying Islands', nativeName: 'United States Minor Outlying Islands', dialCode: '+1', flag: '🇺🇲' },
  { code: 'UY', name: 'Uruguay', nativeName: 'Uruguay', dialCode: '+598', flag: '🇺🇾' },
  { code: 'UZ', name: 'Uzbekistan', nativeName: 'Oʻzbekiston', dialCode: '+998', flag: '🇺🇿' },
  { code: 'VU', name: 'Vanuatu', nativeName: 'Vanuatu', dialCode: '+678', flag: '🇻🇺' },
  { code: 'VE', name: 'Venezuela', nativeName: 'Venezuela', dialCode: '+58', flag: '🇻🇪' },
  { code: 'VN', name: 'Vietnam', nativeName: 'Việt Nam', dialCode: '+84', flag: '🇻🇳' },
  { code: 'VG', name: 'Virgin Islands (British)', nativeName: 'British Virgin Islands', dialCode: '+1284', flag: '🇻🇬' },
  { code: 'VI', name: 'Virgin Islands (U.S.)', nativeName: 'United States Virgin Islands', dialCode: '+1340', flag: '🇻🇮' },
  { code: 'WF', name: 'Wallis and Futuna', nativeName: 'Wallis-et-Futuna', dialCode: '+681', flag: '🇼🇫' },
  { code: 'EH', name: 'Western Sahara', nativeName: 'الصحراء الغربية', dialCode: '+212', flag: '🇪🇭' },
  { code: 'YE', name: 'Yemen', nativeName: 'اليمن', dialCode: '+967', flag: '🇾🇪' },
  { code: 'ZM', name: 'Zambia', nativeName: 'Zambia', dialCode: '+260', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', nativeName: 'Zimbabwe', dialCode: '+263', flag: '🇿🇼' },
];

export const getCountries = (codes: string[] = []): Country[] => {
  if (codes.length === 0) return countries;
  const touchedCodes: string[] = codes.map((code: string) => code.toUpperCase());
  return countries.reduce((accur: Country[], curItem: Country) => {
    const found = touchedCodes.includes(curItem.code.toUpperCase());
    if (!found) return accur;
    return [...accur, curItem];
  }, []);
};

const matches = (country: Country, query: string) => country.name.toLowerCase().includes(query)
  || country.code.toLowerCase().includes(query)
  || country.dialCode.includes(query)
  || country.nativeName.includes(query);

export const filter = (pQuery: string): Country[] => {
  const query = pQuery.trim().toLowerCase();
  if (query.length === 0) return countries;
  return countries.filter((country: Country) => matches(country, query));
};

export const find = (pCode: string): Country | undefined => {
  const code = pCode.trim().toUpperCase();
  return countries.find((country: Country) => country.code === code);
};
